### ISSUE TITLE
Scroll bug when part of Flex widget

### ISSUE THREAD

**Issue by arthmis** [linebender/druid#1491]
There seems to be a bug when dragging a scrollbar when the `scroll` widget is a child of a `flex` widget. The minimum example is
```rust
use druid::widget::Flex;
use druid::widget::Label;
use druid::widget::Scroll;
use druid::AppLauncher;
use druid::Color;
use druid::Widget;
use druid::WidgetExt;
use druid::WindowDesc;
fn main() {
    let window = WindowDesc::new(test_scroll)
        .title("Scroll")
        .window_size((500.0, 500.0));
    AppLauncher::with_window(window)
        .launch("data".to_string())
        .unwrap()
}

fn test_scroll() -> impl Widget<String> {
    let label = Scroll::new(
        Label::new("Test scroll")
            .fix_height(100.0)
            .fix_width(6000.0)
            .background(Color::GRAY),
    );
    Flex::column().with_child(label)
}
```
I'm on Windows 10. I am using latest version of druid master branch. 

https://user-images.githubusercontent.com/25536767/103368194-f7539f80-4a94-11eb-8ab5-c00986f61344.mp4

This seems to only happen when `scroll` is part of `flex`. I haven't tried other combinations of widgets with `scroll`.

**Comment by cmyr** [comment]
Any chance this is fixed by #1475?

**Comment by arthmis** [comment]
That did not fix it, however the behavior is slightly different now:

https://user-images.githubusercontent.com/25536767/103368714-3fbf8d00-4a96-11eb-9d6f-9eaefcf2a102.mp4

**Comment by arthmis** [comment]
I started changing the window size and the size of the label and I noticed that at a certain proportion between the window size and the label size, the scroll behavior changes? (Question because I don't know if the proportion actually matters) So going off the example I used. Setting the label height to `250.0` exhibits normal scroll behavior as far as I'm aware. I then tried `225.0` and it started exhibiting the issue, but it wasn't as bad as when the size is at `100.0`. I'll put some videos of what it looks like at each.

This is at height `225.0` for the Label - window size is (500, 500)

https://user-images.githubusercontent.com/25536767/103369860-35eb5900-4a99-11eb-9616-9f4cdeb375f1.mp4

This is at height `230.0` for the Label - window size is (500, 500)

https://user-images.githubusercontent.com/25536767/103369873-3d126700-4a99-11eb-8bfb-92a4e612900c.mp4

At height of `240.0` the problem is almost eliminated and at `250.0` it is basically gone. At least I don't notice it. Another thing I noticed is that when I ran the code when the label height was `230.0` it would get worse when I resize the window wider. Making the window taller didn't make a visible difference.

**Comment by arthmis** [comment]
@cmyr I take back what I said about that that PR #1475. It didn't seem to make any difference.

**Comment by arthmis** [comment]
So changing the width of the window from 500 to greater does make the behavior go from working correctly to worse. I don't know what could cause the issue. Changing around the width of the label and that width of the window changes the behavior of scroll.

**Comment by derekdreery** [comment]
Sorry to +1, but I've had this issue too.

**Comment by cmyr** [comment]
thanks for the detailed info!

**Comment by tirix** [comment]
It appears line 312 of scroll_component.rs has a typo (height instead of width)!
I'll post a PR.
