### ISSUE TITLE
Can't cross-compile "calc" example to i686-pc-windows-gnu

### ISSUE THREAD

**Issue by vi** [linebender/druid#9]
```
   Compiling druid-win-shell v0.1.1
error[E0308]: mismatched types
   --> /home/vi/.cargo/registry/src/github.com-1ecc6299db9ec823/druid-win-shell-0.1.1/src/window.rs:809:48
    |
809 |         SetWindowLongPtrW(hwnd, GWLP_USERDATA, wndproc_ptr as LONG_PTR);
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^ expected i32, found isize
```

This particular error does not occur for `--target x86_64-pc-windows-gnu`.

Adding `as i32` resolves the error and produces an exe (not runnable with Wine although due to d2d1 not having been implemented enough).

**Comment by IslandUsurper** [comment]
@vi, does it work for other examples? I have the same issue when I tried to use druid in my own project.

**Comment by IslandUsurper** [comment]
Of course it doesn't. druid_win_shell doesn't compile, so nothing that relies on it can compile.

**Comment by vi** [comment]
@IslandUsurper , Does it work if you patch `druid`, adding that `as i32`?

**Comment by IslandUsurper** [comment]
I'm sure it does, but I don't think that's the right solution. Instead, it looks like winapi needs to fix how it defines SetWindowLongPtrW (and friends) on x86 arch. Right now it aliases it to SetWindowLongW (etc), but that function takes a `LONG` instead of a `LONG_PTR`, which is what's going to be passed to it. And Rust doesn't consider `isize` and `i32` to be the same type, even when they are the same size.

**Comment by IslandUsurper** [comment]
I'm going to check this theory, and if it works, I'll file a PR against winapi and link it here.

**Comment by IslandUsurper** [comment]
retep998/winapi-rs#735 is now a thing.

**Comment by raphlinus** [comment]
@IslandUsurper Thanks for looking into this! It's not obvious to me whether this should be solved in winapi or at the next level above, but sounds like we have at the very least a plausible solution.

**Comment by crumblingstatue** [comment]
This is still a problem. I ran into this while trying to cross-compile for i686-pc-windows-gnu.
Changing it to `style as _` makes it work.
If I submit a pull request with that change, would it be acceptable?

**Comment by cmyr** [comment]
@crumblingstatue I would accept that PR.

**Comment by crumblingstatue** [comment]
I believe this issue can be closed now, unless we want to keep it open for tracking the winapi-rs pull request.

**Comment by cmyr** [comment]
I think our solution is acceptable long-term.
